### ISSUE TITLE
Style OpenLayers  local to angular component

### ISSUE THREAD

**Issue by marksmall** [edina/mapuse#3]
When I tried to style OpenLayers 3 widgets locally to the component it failed as the DOM element was created outside the component. I was only ever able to style OpenLayers 3 components at the global level. This is not sufficient for our needs and needs to be fixed.

**Comment by agxs** [comment]
Probably because the view component is set to emulate the shadow dom. This means styles are local only to the component. Each component can be individually changed to use `ViewEncapsulation.None` in the `@Component` config.
