### ISSUE TITLE
Style each client separately

### ISSUE THREAD

**Issue by marksmall** [edina/mapuse#4]
The UI will provide various **views** to the app e.g. OS, Geology, DfS, DfC etc. Each client needs to be treated as a separate app or at least each should have the ability to have a completely different **Look & Feel**.

**Comment by agxs** [comment]
Some notes on theming using Material:

https://material.angular.io/guide/theming

**Comment by marksmall** [comment]
I did a bit of googling about theming in Angular 2 and came across the following pages that may be useful:

* http://stackoverflow.com/questions/38193898/implementing-theme-in-angular2
* https://angular.io/docs/ts/latest/guide/component-styles.html
* http://stackoverflow.com/questions/36516198/same-component-different-styles/36516274#36516274
* http://stackoverflow.com/questions/39643042/load-css-file-dynamically-for-theming
* http://stackoverflow.com/questions/36531486/dynamic-styleurls-in-angular-2
The above links are in no particular order but I would give weight to the angular.io **Component Styles** page.

There appears to be 2 real approaches to investigate **host-context** and overriding @Component function with our own that adds custom CSS (See the last link for a better explanation).

**Comment by agxs** [comment]
I believe `:host-context` only works when using the native shadow DOM, which only works in Chrome and Safari right now.

**Comment by agxs** [comment]
Theming overrides seem to work pretty well. A marker is placed at the top level of the document which allows styles to be adjusted depending on what this marker is. So by default, the `primary`, `accent` and `warn` colours are different per client.

The question is how much do we want to be able to customise. More complex customisations probably need to be dealt with on a per component basis. For example annotation tools could have an `@Input` property which determines what annotation icon to use.
